---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.6
  - name: freebsd-11.0

suites:
  - name: recipe
    run_list:
      - recipe[test_tar::recipe]
  - name: resource
    run_list:
      - recipe[test_tar::resource]
